# Generated by Django 4.2.7 on 2023-11-28 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cli', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('dni', models.PositiveSmallIntegerField()),
                ('mail', models.EmailField(max_length=150)),
                ('telefono', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_emp', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.PositiveIntegerField()),
                ('dni', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_hab', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('hab_ocupada', models.BooleanField(default=False)),
                ('piso', models.PositiveSmallIntegerField()),
                ('numero_habitacion', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Habitacion',
                'verbose_name_plural': 'Habitaciones',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id_puesto', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoHab',
            fields=[
                ('id_tipo', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cant_per', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('mail', models.EmailField(max_length=150)),
                ('es_emp', models.BooleanField()),
                ('id_cli', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.cliente')),
                ('id_emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.empleado')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ing', models.DateTimeField()),
                ('fecha_egr', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('id_cli', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.cliente')),
                ('id_hab', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.habitacion')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.tipohab'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.puesto'),
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('id_emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.empleado')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.reserva')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
    ]
